"""
Files used by Docker / GitHub Actions so inference category stays in sync with ``set``.

``python -m api.inference_model_cli set <category>`` rewrites:

- ``deploy/docker-inference.env`` — ``docker compose`` ``env_file`` (local runs).
- ``deploy/ci_inference_category`` — single line, no variable name; deploy workflow
  reads it into ``ISOCOURT_INFERENCE_CATEGORY`` so the “copy one .pth” step matches CI.
"""
from __future__ import annotations

import os
from typing import List


def deploy_dir(backend_root: str) -> str:
    return os.path.join(os.path.abspath(backend_root), "deploy")


def sync_inference_category_for_deploy(backend_root: str, category: str) -> List[str]:
    """Write deploy helper files. Returns absolute paths written."""
    d = deploy_dir(backend_root)
    os.makedirs(d, exist_ok=True)
    written: List[str] = []

    env_path = os.path.join(d, "docker-inference.env")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by: python -m api.inference_model_cli set <category>\n")
        f.write("# Do not hand-edit; run the CLI again to change.\n")
        f.write(f"ISOCOURT_INFERENCE_CATEGORY={category}\n")
    written.append(env_path)

    ci_path = os.path.join(d, "ci_inference_category")
    with open(ci_path, "w", encoding="utf-8") as f:
        f.write(category.strip())
    written.append(ci_path)

    return written
