import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'node:fs'
import path from 'node:path'

const INDEXABLE = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/analyze', changefreq: 'weekly', priority: '0.9' },
  { path: '/live', changefreq: 'weekly', priority: '0.9' },
  { path: '/faq', changefreq: 'monthly', priority: '0.8' },
  { path: '/glossary', changefreq: 'monthly', priority: '0.7' },
  { path: '/compare', changefreq: 'monthly', priority: '0.8' },
  { path: '/what-is-ai-badminton-stroke-analysis', changefreq: 'monthly', priority: '0.85' },
  { path: '/privacy', changefreq: 'yearly', priority: '0.3' },
  { path: '/terms', changefreq: 'yearly', priority: '0.3' },
]

/** Emit robots.txt + absolute sitemap.xml into dist when VITE_SITE_URL is set. */
function seoStaticFilesPlugin(siteUrl) {
  const origin = (siteUrl || '').replace(/\/$/, '')
  return {
    name: 'isocourt-seo-static-files',
    closeBundle() {
      const outDir = path.resolve(__dirname, 'dist')
      if (!fs.existsSync(outDir)) return

      const sitemapBody = INDEXABLE.map(
        ({ path: p, changefreq, priority }) => {
          const loc = origin ? `${origin}${p === '/' ? '/' : p}` : p
          return `  <url><loc>${loc}</loc><changefreq>${changefreq}</changefreq><priority>${priority}</priority></url>`
        },
      ).join('\n')

      const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapBody}
</urlset>
`
      fs.writeFileSync(path.join(outDir, 'sitemap.xml'), sitemap)

      const robots = [
        '# IsoCourt — generated by Vite build',
        'User-agent: *',
        'Allow: /',
        '',
        origin ? `Sitemap: ${origin}/sitemap.xml` : '# Set VITE_SITE_URL to emit: Sitemap: https://your-domain/sitemap.xml',
        '',
      ].join('\n')
      fs.writeFileSync(path.join(outDir, 'robots.txt'), robots)
    },
  }
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  const siteUrl = env.VITE_SITE_URL || 'https://www.isocourt.fit'

  return {
    plugins: [react(), seoStaticFilesPlugin(siteUrl)],
    server: {
      allowedHosts: true,
    },
  }
})
