#!/usr/bin/env bash
# Make MediaPipe PoseLandmarker work on headless cluster nodes (no sudo).
#
# Usage (on nd17, after conda activate isocourt):
#   cd ~/IsoCourt
#   ./scripts/cluster/setup_mediapipe_gl.sh
#   source scripts/cluster/mediapipe_gl.env
#   python -c "from core.pose_utils import PoseEstimator; PoseEstimator(); print('MediaPipe OK')"
#
# Then build pose cache on-cluster:
#   python backend/pipelines/training/build_full_pose_cache.py \
#     --data-root backend/data \
#     --list-file backend/data/transformed_combined_rounds_output_en_evals_translated.json \
#     --output backend/models/pose_cache_span_linspace.pt \
#     --sampling span_linspace \
#     --checkpoint-every 500

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT_ENV="${REPO_ROOT}/scripts/cluster/mediapipe_gl.env"

if [[ -z "${CONDA_PREFIX:-}" ]]; then
  echo "Activate your conda env first, e.g.: conda activate isocourt" >&2
  exit 1
fi

mkdir -p "${CONDA_PREFIX}/lib"

find_system_lib() {
  local name="$1"
  local hit=""
  if [[ -n "${CONDA_PREFIX:-}" && -e "${CONDA_PREFIX}/lib/${name}" ]]; then
    printf '%s' "${CONDA_PREFIX}/lib/${name}"
    return
  fi
  if command -v ldconfig &>/dev/null; then
    hit="$(ldconfig -p 2>/dev/null | awk -v n="${name}" '$1 == n { print $NF; exit }')"
  fi
  if [[ -z "${hit}" ]]; then
    hit="$(find /usr/lib /usr/lib64 /lib /lib64 "${CONDA_PREFIX:-/nonexistent}/lib" -name "${name}" 2>/dev/null | head -1 || true)"
  fi
  printf '%s' "${hit}"
}

link_into_conda() {
  local soname="$1"
  local src="$2"
  local dest="${CONDA_PREFIX}/lib/${soname}"
  if [[ -z "${src}" || ! -e "${src}" ]]; then
    echo "  missing ${soname} on system" >&2
    return 1
  fi
  ln -sfn "${src}" "${dest}"
  echo "  linked ${dest} -> ${src}"
}

echo "CONDA_PREFIX=${CONDA_PREFIX}" >&2
echo "Linking system GLES/EGL into conda lib (no sudo)..." >&2

LIBS_OK=0
link_into_conda "libGLESv2.so.2" "$(find_system_lib libGLESv2.so.2)" && LIBS_OK=1 || true
link_into_conda "libGLESv2.so" "$(find_system_lib libGLESv2.so)" || true
link_into_conda "libEGL.so.1" "$(find_system_lib libEGL.so.1)" || true
link_into_conda "libGL.so.1" "$(find_system_lib libGL.so.1)" || true

if [[ "${LIBS_OK}" -eq 0 ]]; then
  echo "Installing conda-forge GL packages into ${CONDA_PREFIX}..." >&2
  conda install -y -c conda-forge libglvnd libglvnd-gles mesalib libegl libgl || true
  LIBS_OK=0
  link_into_conda "libGLESv2.so.2" "$(find_system_lib libGLESv2.so.2)" && LIBS_OK=1 || true
  link_into_conda "libEGL.so.1" "$(find_system_lib libEGL.so.1)" || true
  link_into_conda "libGL.so.1" "$(find_system_lib libGL.so.1)" || true
fi

if [[ "${LIBS_OK}" -eq 0 ]]; then
  echo >&2
  echo "Could not find libGLESv2.so.2 on system or via conda." >&2
  echo "This node cannot run MediaPipe without admin-installed mesa/GLES libs." >&2
  echo "Build pose cache on your Mac and rsync backend/models/pose_cache_span_linspace.pt" >&2
  exit 1
fi

# Optional: pull more GLVND pieces from conda-forge if still broken
if ! python -c "import ctypes; ctypes.CDLL('libGLESv2.so.2')" 2>/dev/null; then
  echo "Installing conda-forge libglvnd packages..." >&2
  conda install -y -c conda-forge libglvnd libglvnd-gles mesalib || true
fi

{
  echo "# Generated by scripts/cluster/setup_mediapipe_gl.sh"
  echo "export LD_LIBRARY_PATH=\"${CONDA_PREFIX}/lib:\${LD_LIBRARY_PATH:-}\""
  echo "export EGL_PLATFORM=surfaceless"
  echo "export LIBGL_ALWAYS_SOFTWARE=1"
} > "${OUT_ENV}"

# shellcheck disable=SC1090
source "${OUT_ENV}"

echo "Wrote ${OUT_ENV}" >&2
echo "Testing MediaPipe..." >&2
cd "${REPO_ROOT}"
export PYTHONPATH="${REPO_ROOT}/backend:${PYTHONPATH:-}"
python -c "from core.pose_utils import PoseEstimator; PoseEstimator(); print('MediaPipe OK')"

echo "Success. Before pose-cache build or training with MediaPipe, run:" >&2
echo "  source scripts/cluster/mediapipe_gl.env" >&2
